
<li class="dropdown">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <span class="current-color">
            <?php echo $this->ztbTranslate('Black'); ?>
        </span>&nbsp;
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="black"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="black">
                <?php echo $this->ztbTranslate('Black'); ?>
            </a>
        </li>
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="silver"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="silver">
                <?php echo $this->ztbTranslate('Silver'); ?>
            </a>
        </li>
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="gray"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="gray">
                <?php echo $this->ztbTranslate('Gray'); ?>
            </a>
        </li>
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="maroon"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="maroon">
                <?php echo $this->ztbTranslate('Maroon'); ?>
            </a>
        </li>
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="red"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="red">
                <?php echo $this->ztbTranslate('Red'); ?>
            </a>
        </li>
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="purple"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="purple">
                <?php echo $this->ztbTranslate('Purple'); ?>
            </a>
        </li>
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="green"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="green">
                <?php echo $this->ztbTranslate('Green'); ?>
            </a>
        </li>
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="olive"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="olive">
                <?php echo $this->ztbTranslate('Olive'); ?>
            </a>
        </li>
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="navy"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="navy">
                <?php echo $this->ztbTranslate('Navy'); ?>
            </a>
        </li>
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="blue"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="blue">
                <?php echo $this->ztbTranslate('Blue'); ?>
            </a>
        </li>
        <li>
            <div class="wysihtml5-colors" data-wysihtml5-command-value="orange"></div>
            <a class="wysihtml5-colors-title" data-wysihtml5-command="foreColor" data-wysihtml5-command-value="orange">
                <?php echo $this->ztbTranslate('Orange'); ?>
            </a>
        </li>
    </ul>
</li>
