
<li class="dropdown">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-font"></i>&nbsp;
        <span class="current-font">
            <?php echo $this->ztbTranslate('Normal Text'); ?>
        </span>&nbsp;
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        <li>
            <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="div">
                <?php echo $this->ztbTranslate('Normal Text'); ?>
            </a>
        </li>
        <li>
            <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1">
                <?php echo $this->ztbTranslate('H1'); ?>
            </a>
        </li>
        <li>
            <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2">
                <?php echo $this->ztbTranslate('H2'); ?>
            </a>
        </li>
        <li>
            <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h3">
                <?php echo $this->ztbTranslate('H3'); ?>
            </a>
        </li>
        <li>
            <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h4">
                <?php echo $this->ztbTranslate('H4'); ?>
            </a>
        </li>
        <li>
            <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h5">
                <?php echo $this->ztbTranslate('H5'); ?>
            </a>
        </li>
        <li>
            <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h6">
                <?php echo $this->ztbTranslate('H6'); ?>
             </a>
        </li>
    </ul>
</li>
