<li>
    <div class="btn-group">
        <a class="btn" data-wysihtml5-command="justifyLeft" title="<?php echo $this->ztbTranslate('Align Left'); ?>">
            <i class="icon-align-left"></i>
        </a>
        <a class="btn" data-wysihtml5-command="justifyCenter" title="<?php echo $this->ztbTranslate('Align Center'); ?>">
            <i class="icon-align-center"></i>
        </a>
        <a class="btn" data-wysihtml5-command="justifyRight" title="<?php echo $this->ztbTranslate('Align Right'); ?>">
            <i class="icon-align-left"></i>
        </a>
        <a class="btn" data-wysihtml5-command="justifyFull" title="<?php echo $this->ztbTranslate('Align Justify'); ?>">
            <i class="icon-align-justify"></i>
        </a>
    </div>
</li>
