<li>
    <div class="btn-group">
        <a class="btn" data-wysihtml5-command="insertUnorderedList" title="<?php echo $this->ztbTranslate('Unordered List'); ?>">
            <i class="icon-list"></i>
        </a>
        <a class="btn" data-wysihtml5-command="insertOrderedList" title="<?php echo $this->ztbTranslate('Ordered List'); ?>">
            <i class="icon-th-list"></i>
        </a>
        <a class="btn" data-wysihtml5-command="Outdent" title="<?php echo $this->ztbTranslate('Outdent'); ?>">
            <i class="icon-indent-right"></i>
        </a>
        <a class="btn" data-wysihtml5-command="Indent" title="<?php echo $this->ztbTranslate('Indent'); ?>">
            <i class="icon-indent-left"></i>
        </a>
    </div>
</li>
